spring:
  application:
    name: Gate
server:
  port: 1111
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
springdoc:
  swagger-ui:
    url: /swagger-ui.html